### ISSUE TITLE
asbuild: add subcommands

### ISSUE THREAD

**Issue by willemneal** [near/lang-DAO-grants#9]
[Asbuild](https://github.com/assemblyscript/asbuild) tries to mimic Rust Cargo functionality, by being an all-in-one tool for building, testing, formatting, etc AssemblyScript projects. Right now however it has only very basic functionality.

## asb fmt
We would like asb fmt command to invoke eslint with AssemblyScript-friendly configuration on a given AssemblyScript project.

## asb test
We would like asb test command to find and execute as-pect tests on a given AssemblyScript project.

## asb init
We would like asb init to create scaffolding for an AssemblyScript project, with tiny program that prints Hello World and tiny example of as-pect test. Similar to cargo init in Rust.

NEAR offers anyone who implements it 2000 NEAR tokens.

**Comment by yjhmelody** [comment]
I also agree that it is necessary to integrate these functions into asb. I have written simple package management tools for other languages before, with similar functions, but relatively simple.

**Comment by ashutoshvarma** [comment]
Hi @willemneal, I'm interested in working on this. 
`asb test` and `asb fmt` seems straightforward but do we really need to print Hello World, I mean we need to export `console.log` in the loader that might not be beginner-friendly, a simple [`add` function](https://wasmbyexample.dev/examples/hello-world/hello-world.assemblyscript.en-us.html) would be fine also I think?

I have started with `asb init` and will open a draft PR once its implemented

**Comment by yjhmelody** [comment]
It’s a pity that I was already investigating eslint for this project, and I found that many borders could not be handled well.
